// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNZoi27IP1bMb65MVgKlQqEtYHfvkHD3Q',
    appId: '1:969146186573:web:ec3ac0b16b54635313d504',
    messagingSenderId: '969146186573',
    projectId: 'elkapede',
    authDomain: 'elkapede.firebaseapp.com',
    databaseURL: 'https://elkapede-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elkapede.firebasestorage.app',
    measurementId: 'G-ZNH7QPG9Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQYU2GMVItTxtWggbVGPz3p3pbB-gfuqw',
    appId: '1:969146186573:android:b278c05afbf8f8ba13d504',
    messagingSenderId: '969146186573',
    projectId: 'elkapede',
    databaseURL: 'https://elkapede-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elkapede.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQs_mAvTnAuaXS95HfOK6-I0Qcxltj7U4',
    appId: '1:969146186573:ios:e779240ab38bd3a213d504',
    messagingSenderId: '969146186573',
    projectId: 'elkapede',
    databaseURL: 'https://elkapede-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elkapede.firebasestorage.app',
    androidClientId: '969146186573-2didme4rte70ium21i10vaaeshgscukb.apps.googleusercontent.com',
    iosClientId: '969146186573-mgedje1pfc40r6ujhc0g115h04omgfpd.apps.googleusercontent.com',
    iosBundleId: 'com.elkapede.elkadigi',
  );
}
